import Footer from '@/components/shared/Footer';
import NavBar from '@/components/shared/NavBar';
import Category from '@/components/utility/Category';
import Head from 'next/head';
import React from 'react';

const serviceDetails = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
            </Head>
            <main>
                <NavBar />
                <div>
                    <div className='position-relative details_package_hero'>
                        <div>
                            <img className='img-fluid w-100' src="../assets/images/bg-2.jpg" alt="" />
                        </div>
                        <div className='content w-100 py-5'>
                            <div className="container">
                                <div className='d-flex'>
                                    <div className='text-warning me-3'>
                                        <span className='me-1'><i className="fa-solid fa-star"></i></span>
                                        <span className='me-1'><i className="fa-solid fa-star"></i></span>
                                        <span className='me-1'><i className="fa-solid fa-star"></i></span>
                                        <span className='me-1'><i className="fa-solid fa-star"></i></span>
                                        <span className='me-1'><i className="fa-regular fa-star"></i></span>
                                    </div>
                                    <span>5 review</span>
                                </div>
                                <h2 className='fs-2 fw-bold mt-2'>Card Title</h2>
                                <div><span className='colored fs-3 fw-bold'>160$</span>/per person</div>
                                <button className='primary-btn mt-3'>Pay for Booking</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="container">
                    <div className='row'>
                        <div className='col-md-8 '>
                            <div>
                                <h1 className='mt-3'>Overview</h1>
                                <p className='mt-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum est veniam eum molestiae labore nulla sit natus quo odio ducimus autem fuga temporibus voluptatem assumenda dignissimos beatae, mollitia voluptates optio corrupti! Labore sint, doloremque eligendi iusto adipisci obcaecati odio animi veritatis perferendis ad dolores totam nihil eos porro cumque id saepe pariatur eveniet explicabo molestiae earum. Et id temporibus minima modi quasi suscipit similique, iusto, ut voluptates nesciunt incidunt fugit quis doloremque ducimus omnis asperiores repellendus illum dolorem nemo! Laboriosam.</p>
                                <div className='mt-5'>
                                    <img className='w-100 img-fluid rounded-4' src="../assets/images/bg-1.jpeg" alt="" />
                                </div>
                            </div>
                        </div>
                        <div className='col-md-4'>
                            <div>
                                <form className='submit-form p-5' action="">
                                    <input className='form-control my-2' type="text" placeholder='First Name' />
                                    <input className='form-control my-2' type="text" placeholder='First Name' />
                                    <input className='form-control my-2' type="text" placeholder='First Name' />
                                    <input className='form-control my-2' type="text" placeholder='First Name' />
                                    <input className='form-control my-2' type="text" placeholder='First Name' />
                                    <input type="submit" className='btn btn-primary' />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <Footer />
            </main>
        </>
    );
};

export default serviceDetails;