import Footer from '@/components/shared/Footer';
import NavBar from '@/components/shared/NavBar';
import Category from '@/components/utility/Category';
import Head from 'next/head';
import React from 'react';

const postDetails = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
            </Head>
            <main>
                <NavBar />
                <div className="container">
                    <div className='row' style={{ marginTop: '200px' }}>
                        <div className='col-md-8 '>
                            <div>
                                <div>
                                    <Category>travel</Category>
                                </div>
                                <h1 className='mt-3'>This is post title</h1>
                                <div className='text-secondary'>
                                    by <span className='fw-bold me-2'>Admin</span>
                                    -
                                    <span className='fw-bold ms-2'>0 Comments</span>
                                </div>
                                <div className='mt-5'>
                                    <img className='w-100 img-fluid rounded-4' src="../assets/images/bg-1.jpeg" alt="" />
                                </div>
                                <p className='mt-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum est veniam eum molestiae labore nulla sit natus quo odio ducimus autem fuga temporibus voluptatem assumenda dignissimos beatae, mollitia voluptates optio corrupti! Labore sint, doloremque eligendi iusto adipisci obcaecati odio animi veritatis perferendis ad dolores totam nihil eos porro cumque id saepe pariatur eveniet explicabo molestiae earum. Et id temporibus minima modi quasi suscipit similique, iusto, ut voluptates nesciunt incidunt fugit quis doloremque ducimus omnis asperiores repellendus illum dolorem nemo! Laboriosam.</p>
                            </div>
                        </div>
                        <div className='col-md-4 '></div>
                    </div>
                </div>
                <Footer />
            </main>
        </>
    );
};

export default postDetails;